trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - bash: |
            sudo apt-get install google-chrome-stable
            sudo google-chrome --version