# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
stages:
- stage: Deploytotomcat
  jobs:
    - job: One
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - bash: |
            mvn install 
            mvn clean
            mvn clean install
            ls
            pwd
            echo deepak bajaj
        - task: Cache@2
          inputs:
           key: 'maven | "$(Agent.OS)" | **/pom.xml'
           restoreKeys: |
            maven | "$(Agent.OS)"
            maven
           path: $(MAVEN_CACHE_FOLDER)
          displayName: Cache Maven local repo
        - publish: $(System.DefaultWorkingDirectory)/target
          artifact: test123
        - task: TomcatDeployment@1
          inputs:
           TomcatUrl: 'http://18.191.211.62:8888'
           Username: 'bajajd'
           Password: 'Bajaj'
           Warfile: '**/*war'
           Context: '/azure'
           ServerVersion: '7OrAbove'